###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-29 10:37:05
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-09-29 10:37:17
###############################################################

invokables:
	school_data_fieldset_form : Data/Form/SchoolDataFieldsetForm
	school_data_create_form : Data/Form/SchoolDataCreateForm
	school_data_edit_form : Data/Form/SchoolDataEditForm
	school_data_search_form : Data/Form/SchoolDataSearchForm